#!/usr/bin/env sh
# =====================================================================
# Post-provision hook (POSIX / sh)
# Writes a repo-root .env with the SDK's AGENT_LEARNING_* settings and
# prints how to reach the VM that runs the SDK inside the VNet.
# =====================================================================
set -e

HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HOOK_DIR/../.." && pwd)"
ENV_PATH="$REPO_ROOT/.env"

get_val() {
  # get_val NAME [DEFAULT]
  v="$(azd env get-values | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}\$/\1/p")"
  if [ -z "$v" ]; then v="$2"; fi
  printf '%s' "$v"
}

{
  echo '# Generated by _infra/hooks/postprovision.sh - edit by hand to override an azd output.'
  echo 'AGENT_LEARNING_STORE_BACKEND=cosmos'
  echo "AGENT_LEARNING_COSMOS_ENDPOINT=$(get_val AGENT_LEARNING_COSMOS_ENDPOINT)"
  echo "AGENT_LEARNING_COSMOS_DATABASE=$(get_val AGENT_LEARNING_COSMOS_DATABASE dq_rl)"
  echo "AGENT_LEARNING_COSMOS_AUTH_MODE=$(get_val AGENT_LEARNING_COSMOS_AUTH_MODE aad)"
  echo ''
  echo "AZURE_COSMOS_ACCOUNT_NAME=$(get_val AZURE_COSMOS_ACCOUNT_NAME)"
  echo "AZURE_STORAGE_ACCOUNT_NAME=$(get_val AZURE_STORAGE_ACCOUNT_NAME)"
  echo "AZURE_STORAGE_BLOB_ENDPOINT=$(get_val AZURE_STORAGE_BLOB_ENDPOINT)"
  echo "AZURE_RESOURCE_GROUP=$(get_val AZURE_RESOURCE_GROUP)"
  echo "AZURE_LOCATION=$(get_val AZURE_LOCATION)"
  echo "AZURE_VM_NAME=$(get_val AZURE_VM_NAME)"
  echo "AZURE_VM_PRIVATE_IP=$(get_val AZURE_VM_PRIVATE_IP)"
  echo "AZURE_VM_PUBLIC_IP=$(get_val AZURE_VM_PUBLIC_IP)"
} > "$ENV_PATH"

echo "Wrote $ENV_PATH"

VM="$(get_val AZURE_VM_NAME)"
RG="$(get_val AZURE_RESOURCE_GROUP)"
echo ''
echo 'The SDK virtual machine is provisioned inside the VNet.'
echo "  Resource group : $RG"
echo "  VM name        : $VM"
echo "  Connect        : az ssh vm --resource-group $RG --name $VM"
echo '  (or use Azure Bastion / a jumpbox if the VM has no public IP)'
echo 'The VM carries AGENT_LEARNING_* env vars and reaches Cosmos DB + Storage'
echo 'over private endpoints using its system-assigned managed identity.'
