#!/usr/bin/env pwsh
# =====================================================================
# Post-provision hook (Windows / pwsh)
# Writes a repo-root .env with the SDK's AGENT_LEARNING_* settings and
# prints how to reach the VM that runs the SDK inside the VNet.
# =====================================================================
param()
$ErrorActionPreference = 'Stop'

$hookDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $hookDir '..' '..')
$envPath = Join-Path $repoRoot '.env'

$vals = @{}
foreach ($line in (azd env get-values)) {
  if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
    $vals[$matches[1]] = $matches[2].Trim().Trim('"')
  }
}
function Get-Val([string]$n, [string]$d = '') { if ($vals.ContainsKey($n)) { return $vals[$n] } return $d }

$lines = @(
  '# Generated by _infra/hooks/postprovision.ps1 - edit by hand to override an azd output.',
  'AGENT_LEARNING_STORE_BACKEND=cosmos',
  "AGENT_LEARNING_COSMOS_ENDPOINT=$(Get-Val 'AGENT_LEARNING_COSMOS_ENDPOINT')",
  "AGENT_LEARNING_COSMOS_DATABASE=$(Get-Val 'AGENT_LEARNING_COSMOS_DATABASE' 'dq_rl')",
  "AGENT_LEARNING_COSMOS_AUTH_MODE=$(Get-Val 'AGENT_LEARNING_COSMOS_AUTH_MODE' 'aad')",
  '',
  "AZURE_COSMOS_ACCOUNT_NAME=$(Get-Val 'AZURE_COSMOS_ACCOUNT_NAME')",
  "AZURE_STORAGE_ACCOUNT_NAME=$(Get-Val 'AZURE_STORAGE_ACCOUNT_NAME')",
  "AZURE_STORAGE_BLOB_ENDPOINT=$(Get-Val 'AZURE_STORAGE_BLOB_ENDPOINT')",
  "AZURE_RESOURCE_GROUP=$(Get-Val 'AZURE_RESOURCE_GROUP')",
  "AZURE_LOCATION=$(Get-Val 'AZURE_LOCATION')",
  "AZURE_VM_NAME=$(Get-Val 'AZURE_VM_NAME')",
  "AZURE_VM_PRIVATE_IP=$(Get-Val 'AZURE_VM_PRIVATE_IP')",
  "AZURE_VM_PUBLIC_IP=$(Get-Val 'AZURE_VM_PUBLIC_IP')"
)
$lines -join "`n" | Set-Content -Path $envPath -Encoding utf8
Write-Host "Wrote $envPath" -ForegroundColor Green

$vm = Get-Val 'AZURE_VM_NAME'
$rg = Get-Val 'AZURE_RESOURCE_GROUP'
Write-Host ''
Write-Host 'The SDK virtual machine is provisioned inside the VNet.' -ForegroundColor Cyan
Write-Host "  Resource group : $rg"
Write-Host "  VM name        : $vm"
Write-Host '  Connect        : az ssh vm --resource-group ' -NoNewline; Write-Host "$rg --name $vm"
Write-Host '  (or use Azure Bastion / a jumpbox if the VM has no public IP)'
Write-Host 'The VM carries AGENT_LEARNING_* env vars and reaches Cosmos DB + Storage'
Write-Host 'over private endpoints using its system-assigned managed identity.'
